import { INestApplication } from '@nestjs/common';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import {
  SWAGGER_BEARER_AUTH_NAME,
  SWAGGER_REFRESH_COOKIE_AUTH_NAME,
} from './swagger.responses';

export function setupSwagger(app: INestApplication): void {
  const config = new DocumentBuilder()
    .setTitle('CV Builder API')
    .setDescription(
      'API documentation for authentication and user profile management.',
    )
    .setVersion('1.0.0')
    .addBearerAuth(
      {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
        description: 'JWT access token sent in Authorization header.',
      },
      SWAGGER_BEARER_AUTH_NAME,
    )
    .addCookieAuth(
      'refreshToken',
      {
        type: 'apiKey',
        in: 'cookie',
        description:
          'Refresh token cookie generated by login/register endpoints.',
      },
      SWAGGER_REFRESH_COOKIE_AUTH_NAME,
    )
    .build();

  const document = SwaggerModule.createDocument(app, config);

  SwaggerModule.setup('api/docs', app, document, {
    customSiteTitle: 'CV Builder API Docs',
    swaggerOptions: {
      persistAuthorization: true,
    },
  });
}
